insert into login values (1, 'aa', 'aa');
insert into nauczyciel (name, surname, login_id) values ('Jan', 'Kowalski', 1);
insert into test (czas_trwania, data_uruchomienia, data_zakonczenia, nazwa, token, nauczyciel_id) values ('2022-08-29', '2022-08-30', '2022-08-31', 'test1', 'token', 1);
insert into pytanie (tresc, test_id) values ('ssss', '1');
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (true, 'tresc', 1);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc2', 1);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc3', 1);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc4', 1);
insert into pytanie (tresc, test_id) values ('drugie pytanie', '1');
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (true, 'tresc', 2);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc2', 2);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc3', 2);
insert into odpowiedz (czy_poprawna, tresc, pytanie_id) values (false, 'tresc4', 2);