version: '3.1'
services:
  frontend:
    build: ./szybki-test
    container_name: frontend
    image: 'frontend'
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    image: 'backend'
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres